baseURL = '/'
languageCode = 'en-us'
title = 'Ergodic Labs blog'

theme = "terminal"
pagination.pagerSize = 5

# Build settings
publishDir = "docs"

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  # More colors can be created at https://panr.github.io/terminal-css/
  themeColor = "orange"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  readMore = "more"

[params.logo]
  logoText = "Ergodic Labs blog"

# Required for syntax highlighting
[markup.highlight]
  noClasses = false
